### ISSUE TITLE
sprint suporta mais de um parâmetro.

### ISSUE THREAD

**Issue by eduardomarossi** [GiuPassarelli/Embarcados-APS2#12]
https://github.com/GiuPassarelli/Embarcados-APS2/blob/6c0af7520c16c7512380c0163ff944930c45f4c6/MXT_EXAMPLE_USART1/src/main.c#L726-L737

Porque não utilizar
`sprintf(buffer, "%02d:%02d, horas, minutos);`

**Comment by GiuPassarelli** [comment]
cc7ffabc69d9e40d4933949f2712d09a7a184b07
