### ISSUE TITLE
Não consegui compilar o código, Por favor verificar se todos arquivos estão presentes

### ISSUE THREAD

**Issue by eduardomarossi** [GiuPassarelli/Embarcados-APS2#13]
Está dando os seguintes erros ao compilar

Error |   | icons/snowflake.h: No such file or directory | MXT_EXAMPLE_USART1 | C:\Projetos\APS2\Embarcados-APS2\MXT_EXAMPLE_USART1\src\main.c | 79
Error |   | recipe for target 'src/main.o' failed | MXT_EXAMPLE_USART1 | C:\Projetos\APS2\Embarcados-APS2\MXT_EXAMPLE_USART1\Debug\Makefile | 448

**Comment by GiuPassarelli** [comment]
6157727aa5419e8a677ce35ca7ab794c4d17d1b4 favor verificar
