### ISSUE TITLE
Essa variável só é utilizada em update_screen, poderia ser local

### ISSUE THREAD

**Issue by eduardomarossi** [GiuPassarelli/Embarcados-APS2#3]
https://github.com/GiuPassarelli/Embarcados-APS2/blob/6c0af7520c16c7512380c0163ff944930c45f4c6/MXT_EXAMPLE_USART1/src/main.c#L48

**Comment by aleblucher** [comment]
a0af76db7e400303c3740464586a5b03ea4339d5
