### ISSUE TITLE
Essas variáveis não são usadas em interrupção, não precisa ser volatile

### ISSUE THREAD

**Issue by eduardomarossi** [GiuPassarelli/Embarcados-APS2#4]
https://github.com/GiuPassarelli/Embarcados-APS2/blob/6c0af7520c16c7512380c0163ff944930c45f4c6/MXT_EXAMPLE_USART1/src/main.c#L44-L45

**Comment by aleblucher** [comment]
8f451b4b17a8c4eeda67fafa1c9db3500b279688
