### ISSUE TITLE
Variáveis antes de todos os includes e defines

### ISSUE THREAD

**Issue by eduardomarossi** [GiuPassarelli/Embarcados-APS2#5]
https://github.com/GiuPassarelli/Embarcados-APS2/blob/6c0af7520c16c7512380c0163ff944930c45f4c6/MXT_EXAMPLE_USART1/src/main.c#L44-L79

Ideal é ter todas variáveis sempre após includes, defines e typedefs.

**Comment by GiuPassarelli** [comment]
ba813f4b20119c96cfab7f0f3be24aca0a09123f
