### ISSUE TITLE
Código morto / comentado

### ISSUE THREAD

**Issue by eduardomarossi** [GiuPassarelli/Embarcados-APS2#6]
https://github.com/GiuPassarelli/Embarcados-APS2/blob/6c0af7520c16c7512380c0163ff944930c45f4c6/MXT_EXAMPLE_USART1/src/main.c#L119-L120

Ideal é retirar o código e se precisar recuperar via git

**Comment by GiuPassarelli** [comment]
445fa06c74e42ae5ef69ffdefdf24bf7de2a07ce
