### ISSUE TITLE
Desperdício excessivo de memória

### ISSUE THREAD

**Issue by eduardomarossi** [GiuPassarelli/Embarcados-APS2#7]
https://github.com/GiuPassarelli/Embarcados-APS2/blob/6c0af7520c16c7512380c0163ff944930c45f4c6/MXT_EXAMPLE_USART1/src/main.c#L238-L274

O uso de memória está em excesso pelo que a função faz.

1. Nenhum das informações exibida ultrapassam 255 carácteres e todos os buffers tem 256. Poderia ter usado 128 ou 192 que estaria de bom tamanho.

2. Dá para utilizar um buffer só, já que você nunca desenha ao mesmo tempo todos e nem lê os valores.

Enfim, como estamos trabalhando com um "canhão" de controlador e está função não é um loop crítico, não tem problema, mas é importante saber os caminhos caso fosse necessário como otimizar.

**Comment by GiuPassarelli** [comment]
e545cd8796fefef575d0d3b3f5a1e9c392613242
