### ISSUE TITLE
Poderia ter utilizado um switch case ao invés de vários ifs

### ISSUE THREAD

**Issue by eduardomarossi** [GiuPassarelli/Embarcados-APS2#8]
https://github.com/GiuPassarelli/Embarcados-APS2/blob/6c0af7520c16c7512380c0163ff944930c45f4c6/MXT_EXAMPLE_USART1/src/main.c#L283-L316

**Comment by GiuPassarelli** [comment]
05f9a395ea710da5fe57bd565ece0ffa1ab89562
